name: q42plugin
description: A Flutter plugin that gathers Accessibility data from Android and iOS devices.
version: 0.0.1
homepage: https://gitlab.com/katjaaa_1/portfolio/-/tree/main/Flutter/q42plugin

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: q42stats.signify.com.q42plugin
        pluginClass: Q42pluginPlugin
      ios:
        pluginClass: Q42pluginPlugin
